import { mkdir, mkdtemp, readFile, realpath, rename, rm, symlink, writeFile } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import Fastify from "fastify";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { WikiRun } from "@the-way-here/shared";
import { KnowledgeRuntime } from "../../runtime/knowledge-runtime.js";
import { SourceConnections } from "../../runtime/source-connections.js";
import { PageWriter } from "../content/page-writer.js";
import { registerSourceConnectionRoutes } from "../../routes/source-connection-routes.js";
import { createPiTools } from "../../runtime/agent-runtime/pi/pi-tools.js";
const cleanup: Array<() => Promise<void>> = [];
afterEach(async () => { for (const close of cleanup.splice(0)) await close(); });
async function fixture() {
  const temp = await realpath(await mkdtemp(path.join(os.tmpdir(), "twh-linked-")));
  const root = path.join(temp, "workspace");
  const original = path.join(temp, "notes");
  await mkdir(root); await mkdir(original);
  await writeFile(path.join(root, "the-way-here.config.yaml"), "version: 3\ndefaultKnowledgeBase: one\nknowledgeBases:\n  one:\n    paths: {wiki: app/one/wiki, sources: app/one/sources}\n  two:\n    paths: {wiki: app/two/wiki, sources: app/two/sources}\n");
  const knowledge = await KnowledgeRuntime.create(root, "one");
  const runMap = new Map<string, WikiRun>();
  const runs = { get: vi.fn(async (id: string) => runMap.get(id)), hasActiveKnowledgeBaseRun: vi.fn(async () => false), start: vi.fn(async (input: any) => { const run = { ...input, id: `run-${runMap.size}`, status: "running" } as WikiRun; runMap.set(run.id, run); return run; }) };
  const connections = new SourceConnections(knowledge, runs);
  const app = Fastify(); registerSourceConnectionRoutes(app, knowledge, connections);
  cleanup.push(async () => { await app.close(); await connections.close(); await knowledge.close(); await rm(temp, { recursive: true, force: true }); });
  return { root, original, knowledge, connections, runs, runMap, app, temp };
}
describe("read-only connected source directories", () => {
  it("indexes original text without copying it and makes existing read/search flows work", async () => {
    const f = await fixture();
    const words = "# 日记\n这段原话只存在于原始目录。今天在河边散步。";
    await writeFile(path.join(f.original, "日记.md"), words);
    const [connection] = await f.connections.connect("one", f.original, false);
    expect(connection?.fileCount).toBe(1);
    const page = f.knowledge.index.list({ sources: true })[0]!;
    expect(f.knowledge.index.get(page.id)?.markdown).toBe(words);
    expect(f.knowledge.index.search("河边")[0]?.id).toBe(page.id);
    const reference = await readFile(path.join(f.root, page.relativePath), "utf8");
    expect(reference).not.toContain("今天在河边散步");
    expect(reference).toContain("twh_external");
    const writer = new PageWriter(f.knowledge);
    await expect(writer.save(page.id, "不应写入")).rejects.toThrow("原始文件");
    await expect(writer.deleteSource(page.id)).rejects.toThrow("原始文件");
    await expect(writer.rename(page.id, "改名")).rejects.toThrow("原始文件");
    await expect(writer.deleteSourceFolder("外部来源")).rejects.toThrow("原目录");
    expect(await readFile(path.join(f.original, "日记.md"), "utf8")).toBe(words);
    const tools = createPiTools({ cwd: f.root, config: f.knowledge.index.config, mode: "write" });
    const result = await tools.find((tool) => tool.name === "read_file")!.execute("test", { path: page.relativePath });
    expect(JSON.stringify(result)).toContain("河边");
    await expect(tools.find((tool) => tool.name === "write_file")!.execute("test", { path: page.relativePath, content: "修改引用" })).rejects.toThrow("只读");
  });
  it("keeps reference identity across rename and leaves a tombstone after deletion", async () => {
    const f = await fixture(); await writeFile(path.join(f.original, "a.txt"), "记录原文");
    const [connection] = await f.connections.connect("one", f.original, false);
    const page = f.knowledge.index.list()[0]!;
    await rename(path.join(f.original, "a.txt"), path.join(f.original, "b.txt"));
    await f.connections.update("one", connection!.id, false);
    expect(f.knowledge.index.list()[0]?.id).toBe(page.id);
    expect(f.knowledge.index.get(page.id)?.externalSource?.originalPath).toContain("b.txt");
    await rm(path.join(f.original, "b.txt"));
    await f.connections.update("one", connection!.id, false);
    expect(f.knowledge.index.get(page.id)?.externalSource?.status).toBe("unavailable");
    expect(f.knowledge.index.get(page.id)?.markdown).not.toContain("记录原文");
    expect((await f.connections.list("one"))[0]?.pendingCount).toBe(1);
  });
  it("watches modifications and additions, and preserves them across restart", async () => {
    const f = await fixture(); await writeFile(path.join(f.original, "a.md"), "旧内容");
    await f.connections.connect("one", f.original, false);
    await new Promise((resolve) => setTimeout(resolve, 150));
    await writeFile(path.join(f.original, "a.md"), "外部编辑器写入的新内容");
    await writeFile(path.join(f.original, "b.md"), "新增记录");
    await vi.waitFor(() => expect(f.knowledge.index.search("外部编辑器")).toHaveLength(1), { timeout: 6000 });
    expect(f.knowledge.index.list()).toHaveLength(2);
    const second = await KnowledgeRuntime.create(f.root, "one");
    expect(second.index.search("外部编辑器")).toHaveLength(1);
    await second.close();
  });
  it("rejects workspace overlap and symlink escapes, and disconnect never deletes originals", async () => {
    const f = await fixture();
    await expect(f.connections.connect("one", f.root, false)).rejects.toThrow("工作区外");
    await writeFile(path.join(f.temp, "private.md"), "不可读取的文件");
    await symlink(path.join(f.temp, "private.md"), path.join(f.original, "escape.md"));
    await writeFile(path.join(f.original, "a.md"), "真实原文");
    const [connection] = await f.connections.connect("one", f.original, false);
    expect(f.knowledge.index.list()).toHaveLength(1);
    const page = f.knowledge.index.list()[0]!;
    await rm(path.join(f.original, "a.md"));
    await symlink(path.join(f.temp, "private.md"), path.join(f.original, "a.md"));
    await f.knowledge.index.rebuild();
    expect(f.knowledge.index.get(page.id)?.markdown).not.toContain("不可读取的文件");
    await f.connections.disconnect("one", connection!.id);
    expect(await readFile(path.join(f.temp, "private.md"), "utf8")).toBe("不可读取的文件");
    expect(f.knowledge.index.get(page.id)?.externalSource?.status).toBe("unavailable");
  });
  it("binds background builds to the original library and retains changes made during a run", async () => {
    const f = await fixture(); await writeFile(path.join(f.original, "a.md"), "第一版");
    const [connection] = await f.connections.connect("one", f.original, false);
    await f.knowledge.activate("two");
    await f.connections.sync("one", connection!.id);
    expect(f.runs.start.mock.calls[0]?.[0].knowledgeBaseId).toBe("one");
    await writeFile(path.join(f.original, "a.md"), "第二版");
    await f.connections.update("one", connection!.id, false);
    const firstRun = [...f.runMap.values()][0]!; firstRun.status = "completed";
    await f.connections.sync("one", connection!.id);
    expect(f.runs.start).toHaveBeenCalledTimes(2);
    expect(f.knowledge.index.config.knowledgeBaseId).toBe("two");
    expect(f.knowledge.index.list()).toHaveLength(0);
  });
  it("reports unavailable AI and offline directories without losing pending references", async () => {
    const f = await fixture(); await writeFile(path.join(f.original, "a.md"), "原话");
    const [connection] = await f.connections.connect("one", f.original, false);
    f.runs.start.mockRejectedValueOnce(new Error("没有可用的 AI"));
    await f.connections.sync("one", connection!.id);
    expect((await f.connections.list("one"))[0]?.error).toContain("没有可用");
    await rename(f.original, `${f.original}-offline`);
    await f.connections.sync("one", connection!.id);
    expect((await f.connections.list("one"))[0]?.error).toContain("无法同步");
    expect((await f.connections.list("one"))[0]?.pendingCount).toBe(1);
  });
  it("resolves source and Wiki links in both directions, preserving inbound links after a source rename", async () => {
    const f = await fixture();
    await writeFile(path.join(f.original, "A.md"), "# A\n[[./B|另一篇]]");
    await writeFile(path.join(f.original, "B.md"), "# B\n[[wiki/理解#依据|回到理解]]");
    const [connection] = await f.connections.connect("one", f.original, false);
    const a = f.knowledge.index.list().find((page) => page.title === "A")!;
    const b = f.knowledge.index.list().find((page) => page.title === "B")!;
    const wiki = path.join(f.root, "app/one/wiki");
    await mkdir(wiki, { recursive: true });
    await writeFile(path.join(wiki, "理解.md"), `# 理解\n[[${a.id}|来源A]]\n[[${b.relativePath}|来源B]]\n[[./另一页]]`);
    await writeFile(path.join(wiki, "另一页.md"), "# 另一页\n[[./理解]]");
    await f.knowledge.index.rebuild();
    expect(f.knowledge.index.get(a.id)?.outgoingLinks[0]?.resolvedId).toBe(b.id);
    expect(f.knowledge.index.get(a.id)?.renderedMarkdown).toContain(`/page/${b.id.split("/").map(encodeURIComponent).join("/")}`);
    expect(f.knowledge.index.get(b.id)?.incomingLinks.map((page) => page.id)).toContain(a.id);
    expect(f.knowledge.index.get(b.id)?.outgoingLinks[0]?.resolvedId).toBe("wiki/理解");
    expect(f.knowledge.index.get(b.id)?.renderedMarkdown).toContain(`#${encodeURIComponent("依据")}`);
    expect(f.knowledge.index.get("wiki/理解")?.incomingLinks.map((page) => page.id)).toContain(b.id);
    expect(f.knowledge.index.get("wiki/理解")?.outgoingLinks.map((link) => link.resolvedId)).toEqual([a.id, b.id, "wiki/另一页"]);
    await rename(path.join(f.original, "B.md"), path.join(f.original, "C.md"));
    await f.connections.update("one", connection!.id, false);
    expect(f.knowledge.index.get("wiki/理解")?.outgoingLinks[1]?.resolvedId).toBe(b.id);
    expect(f.knowledge.index.get(b.id)?.title).toBe("C");
    expect(f.knowledge.index.get(b.id)?.incomingLinks.map((page) => page.id)).toContain("wiki/理解");
  });
  it("automatically schedules a bound build and clears only a successfully built version", async () => {
    const f = await fixture();
    await f.connections.start();
    await writeFile(path.join(f.original, "a.md"), "自动同步的原文");
    await f.connections.connect("one", f.original, true);
    await vi.waitFor(() => expect(f.runs.start).toHaveBeenCalledTimes(1), { timeout: 7000 });
    expect(f.runs.start.mock.calls[0]?.[0].knowledgeBaseId).toBe("one");
    [...f.runMap.values()][0]!.status = "completed";
    await vi.waitFor(async () => expect((await f.connections.list("one"))[0]?.pendingCount).toBe(0), { timeout: 7000 });
  }, 16000);
  it("rejects a stale library request before creating a directory connection", async () => {
    const f = await fixture();
    const response = await f.app.inject({ method: "POST", url: "/api/source-connections", payload: { knowledgeBaseId: "two", path: f.original, autoBuild: false } });
    expect(response.statusCode).toBe(409);
    expect(await f.connections.list("one")).toHaveLength(0);
  });
});
