import { _electron as electron, expect } from '@playwright/test';
import { cp, mkdir, mkdtemp, writeFile, readFile, rm, realpath } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
const studio=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const root=await realpath(await mkdtemp(path.join(os.tmpdir(),'twh-desktop-check-')));
const linkedDirectory=await realpath(await mkdtemp(path.join(os.tmpdir(),'twh-original-check-')));
await writeFile(path.join(linkedDirectory,'连接原文.md'),'只保留在原目录的第一版');
const captures=path.join(studio,'.impeccable/reviews'); await mkdir(captures,{recursive:true});
await cp(path.join(studio,'../vault/demo'),path.join(root,'vault/demo'),{recursive:true});
await cp(path.join(studio,'../knowledge-engine'),path.join(root,'knowledge-engine'),{recursive:true});
await writeFile(path.join(root,'AGENTS.md'),'Anonymous desktop verification workspace.');
await writeFile(path.join(root,'the-way-here.config.yaml'),'version: 3\ndefaultKnowledgeBase: demo\npaths:\n  skills: knowledge-engine/skills\n  tools: knowledge-engine/tools\n  agentInstructions: AGENTS.md\nknowledgeBases:\n  demo:\n    name: The Way Here 演示 Wiki\n    paths:\n      wiki: vault/demo/wiki\n      sources: vault/demo/sources\nagents:\n  runtimes:\n    codex:\n      enabled: false\n    pi:\n      enabled: false\nvalidation:\n  commands: []\n');
let application;
try {
  application=await electron.launch({ ...(process.env.TWH_DESKTOP_EXECUTABLE ? {executablePath:process.env.TWH_DESKTOP_EXECUTABLE,args:['--diagnostics']} : {args:[path.join(studio,'apps/desktop'),'--diagnostics']}), env:{...process.env,THE_WAY_HERE_VAULT:root,THE_WAY_HERE_KNOWLEDGE_BASE:'demo'},timeout:60000 });
  application.process().stderr.on('data', data => process.stderr.write(data));
  const page=await application.firstWindow({timeout:60000}); await page.waitForLoadState('domcontentloaded');
  const errors=[]; page.on('pageerror', error=>errors.push(error.message));
  await expect(page.locator('h1')).toContainText('欢迎回来');
  const origin=new URL(page.url()).origin;
  expect(new URL(origin).hostname).toMatch(/^workspace-[a-f0-9]+\.localhost$/);
  await page.evaluate(() => (localStorage.setItem('desktop.verify-persistence','kept'), localStorage.setItem('desktop.inspector','true')));
  expect(await page.evaluate(() => typeof window.require)).toBe('undefined');
  expect(await page.evaluate(() => window.desktop.openWindow('https://example.com').then(() => false, () => true))).toBe(true);
  await page.reload();
  expect(await page.evaluate(() => localStorage.getItem('desktop.verify-persistence'))).toBe('kept');
  const invokeMenu=async(label)=> application.evaluate(({Menu},label) => { const walk=(items)=>{for(const item of items){if(item.label===label){item.click();return true;}if(item.submenu&&walk(item.submenu.items))return true;}return false;};if(!walk(Menu.getApplicationMenu().items))throw Error('Missing menu: '+label); },label);
  for (const route of ['/','/questions','/sources','/knowledge','/insights','/timeline','/letters','/relationships','/cards/personal-lines','/cards/cycles','/cards/systems','/mental-models']) {
    console.log('Route',route);
    await page.goto(origin+route); await expect(page.locator('.desktop-sidebar')).toBeVisible();
    await page.locator('h1').first().waitFor(); await page.waitForTimeout(160);
    const geometry=await page.locator('.main-area').evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth}));
    expect(geometry.scroll,route+' horizontal overflow').toBeLessThanOrEqual(geometry.width+2);
    if(['/','/sources','/letters','/relationships','/questions','/knowledge','/insights','/timeline'].includes(route)) await page.screenshot({path:path.join(captures,`desktop-${route==='/'?'today':route.slice(1)}.png`)});
  }
  await invokeMenu('搜索与命令');
  await page.getByRole('combobox').fill('近况回信'); await page.getByRole('combobox').press('Enter'); await expect(page).toHaveURL(/letters/);
  await invokeMenu('AI 协作面板'); await expect(page.locator('.desktop-inspector')).toBeHidden();
  await invokeMenu('AI 协作面板'); await expect(page.locator('.desktop-inspector')).toBeVisible();
  const settingsPromise=application.waitForEvent('window'); await invokeMenu('偏好设置…'); const settings=await settingsPromise; await settings.waitForLoadState('domcontentloaded');
  await expect(settings.getByRole('tab',{name:'AI 助手'})).toBeVisible(); await settings.getByRole('tab',{name:'AI 助手'}).click(); await expect(settings.locator('.ai-configuration')).toBeVisible();
  await settings.screenshot({path:path.join(captures,'desktop-preferences.png')}); await settings.close();
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(win=>win.kind==='main')?.focus());
  const capturePromise=application.waitForEvent('window'); await invokeMenu('随手记'); const capture=await capturePromise; await capture.waitForLoadState('domcontentloaded');
  await capture.getByRole('textbox',{name:'记录标题（可选）'}).fill('桌面验收记录');
  await capture.getByRole('button',{name:'语音说一段',exact:true}).click();
  await capture.getByLabel('口述原话',{exact:true}).fill('这是匿名演示，用于核对语音确认流程。');
  await capture.getByRole('button',{name:'使用这段文字',exact:true}).click();
  await expect(capture.getByRole('textbox',{name:'随手记内容'})).toHaveValue('这是匿名演示，用于核对语音确认流程。');
  await capture.screenshot({path:path.join(captures,'desktop-capture.png')});
  await capture.getByRole('button',{name:'保存记录',exact:true}).click(); await expect(capture.getByRole('status')).toContainText('已保存');
  const pages=await capture.evaluate(()=>fetch('/api/pages?sources=true').then(res=>res.json()));
  const saved=pages.find(item=>item.title==='桌面验收记录'); expect(saved).toBeTruthy();
  const stale=await capture.evaluate(async()=>{const result=await fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/json','X-TWH-Knowledge-Base':'other'},body:JSON.stringify({title:'禁止跨库',markdown:'不能写入',knowledgeBaseId:'demo'})});return result.status;});expect(stale).toBe(409);
  await capture.close();
  await page.goto(origin+'/page/'+saved.id.split('/').map(encodeURIComponent).join('/'));
  await page.locator('.editable-document').waitFor();
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(win=>win.kind==='main')?.focus());
  const readerPromise=application.waitForEvent('window'); await invokeMenu('在独立窗口打开'); const reader=await readerPromise; await reader.waitForLoadState('domcontentloaded');
  await expect(reader.locator('.editable-document')).toBeVisible(); expect(await reader.locator('.editable-document-activate').count()).toBe(0); await reader.close();
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(win=>win.kind==='main')?.focus());
  const focusPromise=application.waitForEvent('window'); await invokeMenu('深入聊聊'); const focus=await focusPromise; await focus.waitForLoadState('domcontentloaded'); await expect(focus.locator('.context-agent-panel')).toBeVisible(); await focus.close();
  await page.goto(origin+'/sources'); await page.getByRole('button',{name:/照片记忆 从一张照片/}).click(); await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.locator('.source-connections-disclosure summary').click();
  await page.locator('.source-connection-add input[type="checkbox"]').uncheck();
  await application.evaluate(({dialog},directory) => { dialog.showOpenDialog=async()=>({canceled:false,filePaths:[directory]}); },linkedDirectory);
  await page.getByRole('button',{name:'连接原始目录',exact:true}).click();
  await expect(page.locator('.source-connections article')).toHaveCount(1);
  const linkedText='来自外部编辑器的第二版\n\n[[wiki/连接验收#依据|查看依据]]';
  await writeFile(path.join(linkedDirectory,'连接原文.md'),linkedText);
  await expect.poll(async()=>page.evaluate(()=>fetch('/api/search?q=来自外部编辑器').then(res=>res.json()).then(rows=>rows.length)),{timeout:10000}).toBe(1);
  const linkedPage=await page.evaluate(()=>fetch('/api/search?q=来自外部编辑器').then(res=>res.json()).then(rows=>rows[0]));
  expect(await readFile(path.join(root,linkedPage.relativePath),'utf8')).not.toContain('来自外部编辑器的第二版');
  await writeFile(path.join(root,'vault/demo/wiki/连接验收.md'),`# 连接验收\n\n## 依据\n[[${linkedPage.id}|回到原文]]`);
  await expect.poll(async()=>page.evaluate(()=>fetch('/api/pages/wiki/连接验收').then(res=>res.ok ? res.json() : null).then(row=>row?.incomingLinks?.length || 0)),{timeout:10000}).toBe(1);
  await page.getByRole('button',{name:'连接原文',exact:true}).click();
  await expect(page.locator('.external-source-notice')).toContainText('原目录只读连接');
  expect(await page.locator('.editable-document-activate').count()).toBe(0);
  await page.screenshot({path:path.join(captures,'desktop-source-connections.png')});
  await page.getByRole('link',{name:'查看依据',exact:true}).click();
  await expect(page).toHaveURL(/#%E4%BE%9D%E6%8D%AE$/);
  await expect(page.getByRole('heading',{name:'依据',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'回到原文',exact:true}).click();
  await expect(page.locator('.external-source-notice')).toBeVisible();
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(win=>win.kind==='main')?.setSize(1100,780));
  for (const route of ['/','/sources','/relationships']) {
    await page.goto(origin+route); await page.locator('h1').first().waitFor();
    const box=await page.locator('.main-area').evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth}));
    expect(box.scroll, 'compact '+route).toBeLessThanOrEqual(box.width+2);
    await page.screenshot({path:path.join(captures,`compact-${route==='/'?'today':route.slice(1)}.png`)});
  }
  expect(errors).toEqual([]);
  await application.close();
  application=await electron.launch({ ...(process.env.TWH_DESKTOP_EXECUTABLE ? {executablePath:process.env.TWH_DESKTOP_EXECUTABLE,args:['--diagnostics']} : {args:[path.join(studio,'apps/desktop'),'--diagnostics']}), env:{...process.env,THE_WAY_HERE_VAULT:root,THE_WAY_HERE_KNOWLEDGE_BASE:'demo'},timeout:60000 });
  const reopened=await application.firstWindow({timeout:60000}); await reopened.waitForLoadState('domcontentloaded');
  await expect(reopened.locator('h1')).toContainText('欢迎回来');
  expect(new URL(reopened.url()).origin).toBe(origin);
  expect(await reopened.evaluate(() => localStorage.getItem('desktop.verify-persistence'))).toBe('kept');
  expect(await reopened.evaluate(()=>fetch('/api/search?q=来自外部编辑器').then(res=>res.json()).then(rows=>rows.length))).toBe(1);
  await reopened.goto(origin+'/sources');
  await reopened.locator('.source-connections-disclosure summary').click();
  await reopened.getByRole('button',{name:'断开连接',exact:true}).click();
  await reopened.getByRole('button',{name:'确认断开',exact:true}).click();
  await expect(reopened.locator('.source-connections article')).toHaveCount(0);
  expect(await readFile(path.join(linkedDirectory,'连接原文.md'),'utf8')).toBe(linkedText);
  console.log('Desktop verified: source/Wiki links, backlinks, heading navigation, connected directories, original-file updates, no copies, readonly sources, connection persistence and safe disconnect; 12 routes, native menus, search, inspector, preferences, voice confirmation, capture persistence, stale-library guard, readonly reader, focus window, photo import, stable workspace storage across app restart, sandbox and IPC rejection.');
} catch(error) { const page=application?.windows()[0]; if(page) { console.log('Failed route',page.url(),(await page.locator('body').innerText()).slice(0,2500)); await page.screenshot({path:path.join(captures,'verification-failure.png')}); } throw error; } finally { await application?.close(); await rm(root,{recursive:true,force:true}); await rm(linkedDirectory,{recursive:true,force:true}); }
